// --------------------------------------------------------
// Code generated by Papyrus Java
// --------------------------------------------------------

package SE_II.Geldautomat;

/************************************************************/
/**
 * 
 */
public class CustomerAccount {
	/**
	 * 
	 */
	private String customerName;
	/**
	 * 
	 */
	private int PIN;
	/**
	 * 
	 */
	private int ID;
	/**
	 * 
	 */
	private EDouble balance;

	/**
	 * 
	 * @param customerName 
	 * @param id 
	 * @param pin 
	 */
	public CustomerAccount(String customerName, int id, int pin) {
	}

	/**
	 * 
	 * @param diff 
	 */
	public void updateBalance(EDouble diff) {
	}

	/**
	 * 
	 * @return 
	 */
	public String getName() {
	}

	/**
	 * 
	 * @return 
	 */
	public int getPIN() {
	}

	/**
	 * 
	 * @return 
	 */
	public int getID() {
	}

	/**
	 * 
	 * @return 
	 */
	public EDouble getBalance() {
	}

	/**
	 * 
	 * @param customerName 
	 */
	public void setCustomerName(String customerName) {
	}
}
