// --------------------------------------------------------
// Code generated by Papyrus Java
// --------------------------------------------------------

package SE_II.Geldautomat;

/************************************************************/
/**
 * 
 */
public class ATM {
	/**
	 * 
	 */
	private CustomerAccount currentCustomer;

	/**
	 * 
	 * @param pin 
	 * @param kundennummer 
	 * @return 
	 */
	public boolean signIn(int pin, int kundennummer) {
	}

	/**
	 * 
	 * @param sum 
	 * @return 
	 */
	public boolean payIn(EDouble sum) {
	}

	/**
	 * 
	 * @param sum 
	 * @return 
	 */
	public boolean payOut(EDouble sum) {
	}

	/**
	 * 
	 * @return 
	 */
	public EDouble getBalance() {
	}

	/**
	 * 
	 */
	public void signOut() {
	}

	/**
	 * 
	 * @param departmentStore 
	 */
	public ATM(DepartmentStore departmentStore) {
	}
}
