// --------------------------------------------------------
// Code generated by Papyrus Java
// --------------------------------------------------------

package SE_II.Geldautomat;

/************************************************************/
/**
 * 
 */
public class ATMApplication {
	/**
	 * 
	 */
	public GUI gui;

	/**
	 * 
	 * @param args 
	 */
	public static void main(String[] args) {
	}

	/**
	 * Private constructor to prevent the creation of instances
	 */
	private ATMApplication() {
	}
}
