// --------------------------------------------------------
// Code generated by Papyrus Java
// --------------------------------------------------------

package SE_II.Geldautomat;

/************************************************************/
/**
 * 
 */
public class DepartmentStore {
	/**
	 * 
	 */
	private String name;
	/**
	 * 
	 */
	private String jsonPathCustomerData = null;

	/**
	 * 
	 */
	public DepartmentStore() {
	}

	/**
	 * 
	 * @return 
	 * @param id 
	 */
	public CustomerAccount getCustomerAccountById(String id) {
	}

	/**
	 * 
	 * @return 
	 * @param customerAccount 
	 */
	public boolean addCustomerAccount(CustomerAccount customerAccount) {
	}

	/**
	 * 
	 * @param id 
	 */
	public void removeCustomerAccountById(String id) {
	}

	/**
	 * 
	 * @return 
	 */
	public String getName() {
	}

	/**
	 * 
	 * @param name 
	 */
	public void setName(String name) {
	}

	/**
	 * 
	 * @param jsonPath 
	 */
	public void loadDataFromFile(String jsonPath) {
	}

	/**
	 * 
	 * @param jsonPath 
	 */
	public void loadCustomerDataFromFile(String jsonPath) {
	}

	/**
	 * 
	 * @return 
	 * @param filePath 
	 */
	private String readJSONFileToString(String filePath) {
	}

	/**
	 * 
	 */
	public void saveCustomerDataToFile() {
	}
}
