// --------------------------------------------------------
// Code generated by Papyrus Java
// --------------------------------------------------------

package SE_II.Geldautomat;

/************************************************************/
/**
 * Extends javax.swing.JFrame (not noted in Papyrus so it must be set manually after code generation)
  * 
 */
public class GUIFrameMenu {
	/**
	 * 
	 * @param atm 
	 */
	public GUIFrameMenu(ATM atm) {
	}
}
