// --------------------------------------------------------
// Code generated by Papyrus Java
// --------------------------------------------------------

package SE_II.Geldautomat;

/************************************************************/
/**
 * 
 */
public class DepartmentStore {
	/**
	 * 
	 */
	private String name;

	/**
	 * 
	 * @param name 
	 */
	public DepartmentStore(String name) {
	}

	/**
	 * 
	 * @return 
	 * @param id 
	 */
	public CustomerAccount getCustomerAccountById(int id) {
	}

	/**
	 * 
	 * @return 
	 * @param customerAccount 
	 */
	public boolean addCustomerAccount(CustomerAccount customerAccount) {
	}

	/**
	 * 
	 * @param id 
	 */
	public void removeCustomerAccountById(int id) {
	}

	/**
	 * 
	 * @return 
	 */
	public String getName() {
	}

	/**
	 * 
	 * @param name 
	 */
	public void setName(String name) {
	}
}
