// --------------------------------------------------------
// Code generated by Papyrus Java
// --------------------------------------------------------

package SE_II.Geldautomat;

/************************************************************/
/**
 * 
 */
public class GUI {
	/**
	 * 
	 */
	private boolean running;

	/**
	 * 
	 * @param departmentStore 
	 */
	public GUI(DepartmentStore departmentStore) {
	}

	/**
	 * 
	 */
	public void start() {
	}

	/**
	 * 
	 */
	public void stop() {
	}
}
