package main;

import java.awt.EventQueue;

// --------------------------------------------------------
// Code generated by Papyrus Java
// Comments and functionality added manually
// --------------------------------------------------------

/************************************************************/
/**
 * Main class for GUI handling
 */
public class GUI {
	
	/**
	 * Current GUI state (true = running, false = stopped)
	 */
	private boolean running;

	/**
	 * Reference to the ATM instance that should be handled
	 */
	private ATM atm;
    
	/**
	 * Standard constructor
	 * @param atm	Reference to the ATM instance that should be handled
	 */
	public GUI(ATM atm) {
		this.atm=atm;
		this.running=false;
	}

	/**
	 * Method to start the GUI (starts the GUIFrame classes)
	 */
	public void start() {
		EventQueue.invokeLater(new Runnable() {
			public void run() {
				try {
					GUIFrameAnmeldung frame = new GUIFrameAnmeldung(atm);
					frame.setVisible(true);
					GUI.this.running=true;
				
				} catch (Exception e) {
					e.printStackTrace();
					GUI.this.running=false;
				}
			}
		});
	}

	/**
	 * Method to stop the GUI
	 */
	public void stop() {
		this.running=false;
	}
}
