// --------------------------------------------------------
// Code generated by Papyrus Java
// --------------------------------------------------------

package SE_II.Geldautomat;

/************************************************************/
/**
 * 
 */
public class ATM {
	/**
	 * 
	 */
	private CustomerAccount currentCustomer;

	/**
	 * 
	 * @param kundennummer 
	 * @param pin 
	 * @return 
	 */
	public boolean signIn(String kundennummer, String pin) {
	}

	/**
	 * 
	 * @param sum 
	 * @return 
	 */
	public boolean payIn(EDouble sum) {
	}

	/**
	 * 
	 * @param sum 
	 * @return 
	 */
	public boolean payOut(EDouble sum) {
	}

	/**
	 * 
	 * @return 
	 */
	public EDouble getBalance() {
	}

	/**
	 * 
	 */
	public void signOut() {
	}

	/**
	 * 
	 */
	public ATM() {
	}

	/**
	 * 
	 */
	private void loadDepartmentStoreData() {
	}
}
