// --------------------------------------------------------
// Code generated by Papyrus Java
// --------------------------------------------------------

package SE_II.Geldautomat;

/************************************************************/
/**
 * 
 */
public class CustomerAccount {
	/**
	 * 
	 */
	private String customerName;
	/**
	 * 
	 */
	private String PIN;
	/**
	 * 
	 */
	private String ID;
	/**
	 * 
	 */
	private EDouble balance;

	/**
	 * 
	 * @param customerName 
	 * @param id 
	 * @param pin 
	 * @param currentBalance 
	 */
	public CustomerAccount(String customerName, String id, String pin, EDouble currentBalance) {
	}

	/**
	 * 
	 * @param diff 
	 */
	public void updateBalance(EDouble diff) {
	}

	/**
	 * 
	 * @return 
	 */
	public String getName() {
	}

	/**
	 * 
	 * @return 
	 */
	public String getPIN() {
	}

	/**
	 * 
	 * @return 
	 */
	public String getID() {
	}

	/**
	 * 
	 * @return 
	 */
	public EDouble getBalance() {
	}

	/**
	 * 
	 * @param customerName 
	 */
	public void setCustomerName(String customerName) {
	}
}
